### PR TITLE
better web worker test

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks, this is awesome! I would kind of prefer to have an additional test (i.e. another radio button with "Web worker, cloned objects") rather than replace the existing one, though. BTW have you tested? What do you see so far?

**Comment by calvinmetcalf** [comment]
less jenking but still some but in direct proportion to the number of records.  Will update it to do so

**Comment by calvinmetcalf** [comment]
ok made it 3 options, also switched the timing from worker side to main thread to better capture the latency involved in sending it to a worker (noticeable for quick things, a drop in the bucket for bigger ones)

**Comment by calvinmetcalf** [comment]
ok also added es6 map and set, and fixed the async promise code to actually catch errors (somebody was passing a promise to then instead of a function which returns a promise, you know there is a really good blog post about catching those kinds of errors you should read :smile: )

**Comment by nolanlawson** [comment]
lol, thanks a bunch! I will merge this asap. Also as for promise errors, I still screw it up constantly - async/await can't come soon enough :stuck_out_tongue:

**Comment by calvinmetcalf** [comment]
I've been using Bluebird.coroutine and liking it quite alot

**Comment by nolanlawson** [comment]
yeah, bluebird 3.0 also apparently warns about that then() issue. need a way to quickly switch between bluebird during testing and lie.polyfill.js during production...

**Pull request merged**
